version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    env_file:
      - ./.env
    volumes:
      - image_data:/images
      - application_form_files:/applicationFormFiles
      - log_data:/logs
volumes:
  image_data:
  log_data:
  application_form_files:
